# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Personal info
name: Amir Askari
title:  Junior Back-End developer
email: askaria079@gmail.com
website: naha7789.github.io
phone: 09195465477
# Social links
github_username:  naha7789
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: amirh_askari
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Amir and I'm a junior Back-End developer. As well as develope feature. I also have experience making software and web apps. I have worked at a number of companies gaining teamwork.

  I am most skilled in: <mark>Python</mark> and <mark>Sleep</mark>
  github: naha7789/naha7789.github.io/images/Amir askari_resume_April 2020.pdf
  
# about_Cv: images/Amir askari_resume_April 2020.pdf 
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

#Technical_skills Section:
#technical_skills Section: Technical

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Sleep
   - Gaming (Dota 2)
   - laugh sometimes
   - [Becoming a good developer]

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
